sources = gui_simple.cpp
objets = $(sources:.c=.o)
GUISIMPLE:$(objets)
	g++ $^ -o $@ -lQtCore -lQtGui
gcc -I  /usr/include/qt4/QtGui/QApplication
gcc -I /usr/include/qt4/QtGui/QPushButton
gcc -I /usr/include/qt4/QtGui/QVBoxLayout
